### ISSUE TITLE
HubSpot CMS Deploy Action Running HubSpot CLI Command for Wrong Version

### ISSUE THREAD

**Issue by thomas-j-moffett** [HubSpot/hubspot-cms-deploy-action#15]
Hi, can someone tell me why this issue is happening? I posted my issue in a thread over on HubSpot community site after a Google search led me there: [https://community.hubspot.com/t5/CMS-Development/npm-install-fail-on-HubSpot-CMS-Deploy-Action/m-p/535716/highlight/true#M26365](https://community.hubspot.com/t5/CMS-Development/npm-install-fail-on-HubSpot-CMS-Deploy-Action/m-p/535716/highlight/true#M26365)

I'd prefer to use the latest version of the HubSpot CLI, but I might be forced to downgrade to 3.0.4, which is the one that the Github Action is trying to use.

**Comment by thomas-j-moffett** [comment]
I think I found some info that might help. In my deploy workflow that runs, Github is pulling from tag v1.4 (which is supposedly the latest version), which is pointing to this commit: https://github.com/HubSpot/hubspot-cms-deploy-action/commit/18869510ce72b289dde63422380cbfbf4a7cb086
![image](https://user-images.githubusercontent.com/22506345/144521693-fc5a37e0-0dbb-4b7b-8957-b4e500685efa.png)


And that is set to run the CLI specifically for version 3.0.4. Is there a reason why you need to specify the version number in HubSpot CMS Deploy Github Action? It just seems like it's causing issues that could be avoided by leaving off the `@VERSION` part, right?

**Comment by thomas-j-moffett** [comment]
I think I have been going down the wrong path with trying to figure this out. So, I think Github Actions might have upgraded their Node/NPM, and now for whatever reason the executable cannot be found when running this command: `npx @hubspot/cli@3.0.9 ...` as it is in the HubSpot action YAML. I was able to reproduce the same issue locally when installing Node version 16.13.1 (and NPM 8.1.2). After switching Node back to version 14.16.0 (and NPM 6.14.11), which I previously had installed, the command worked.

**Comment by anthmatic** [comment]
@thomas-j-moffett thanks for reporting this! I just published a new release (v1.5) that should fix this issue. Feel free to reopen this is the issue still occurs with the latest version.

**Comment by thomas-j-moffett** [comment]
Thanks for the fix! Our builds are working again.
