### ISSUE TITLE
Deploy error in v1.5

### ISSUE THREAD

**Issue by TheWebTech** [HubSpot/hubspot-cms-deploy-action#17]
Issue was reported by Timothy Purdy via our developer slack, log and thread here: https://hubspotdev.slack.com/archives/CLJJXGTC0/p1642089934032300

**Comment by anthmatic** [comment]
This was an issue with the configuration. I've [updated the readme here](https://github.com/HubSpot/hubspot-cms-deploy-action/pull/18) to help make it clearer.
