### ISSUE TITLE
Cannot deploy to production site

### ISSUE THREAD

**Issue by OliverBojahrS24** [HubSpot/hubspot-cms-deploy-action#25]
When deploying to production I receive the following error, while deploying to sandbox works just fine:

> The account ID provided (***) isn't valid. Make sure that account has installed your app before making this call

But the actions are just copies except for trigger and using a different site id. 

I can deploy to production locally using the `hs upload --portal=PROD`

Any hint?

**Comment by BorisWRLB** [comment]
As it seems no one has answered your question, and I suspect something isn't configured correctly, I am making an attempt of helping.
You mention changing the site/portal id, but did you also change the secrets.hubspot_personal_access_key value?
Most likely the value is locally defined in your hubspot.config.yml file, but you didn't change it in your pipeline.

**Comment by OliverBojahrS24** [comment]
@TanyaScales thanks for answering. ... You're right ... my bad.
