### ISSUE TITLE
Suddenly all the action workflow stopped working 

### ISSUE THREAD

**Issue by digitalwoods-suman** [HubSpot/hubspot-cms-deploy-action#34]
We encountered an error during the deployment process, where the system returned the following message:

##[debug]Evaluating condition for step: 'HubSpot Deploy Action'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: HubSpot Deploy Action
##[debug]Loading inputs
##[debug]Evaluating: secrets.HUBSPOT_PORTAL_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'HUBSPOT_PORTAL_ID'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.HUBSPOT_PERSONAL_ACCESS_KEY
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'HUBSPOT_PERSONAL_ACCESS_KEY'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run HubSpot/hubspot-cms-deploy-action@v1.7
##[debug]Evaluating condition for step: 'run'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: run
##[debug]Loading inputs
##[debug]Loading env
Run actions/setup-node@v1
##[debug]isExplicit: 
##[debug]explicit? false
##[debug]isExplicit: 16.[2](https://github.com/Digital-Woods/digital-woods-theme-v2/actions/runs/10448523239/job/28929438043#step:3:2)0.2
##[debug]explicit? true
##[debug]isExplicit: 18.20.4
##[debug]explicit? true
##[debug]isExplicit: 20.16.0
##[debug]explicit? true
##[debug]evaluating [3](https://github.com/Digital-Woods/digital-woods-theme-v2/actions/runs/10448523239/job/28929438043#step:3:3) versions
##[debug]matched: 20.16.0
##[debug]checking cache: /opt/hostedtoolcache/node/20.16.0/x6[4](https://github.com/Digital-Woods/digital-woods-theme-v2/actions/runs/10448523239/job/28929438043#step:3:4)
##[debug]Found tool in cache node 20.16.0 x64
/opt/hostedtoolcache/node/20.16.0/x64/bin/node --version
v20.16.0
/opt/hostedtoolcache/node/20.16.0/x64/bin/npm --version
10.8.1
##[add-matcher]/home/runner/work/_actions/actions/setup-node/v1/.github/tsc.json
##[debug]Added matchers: 'tsc'. Problem matchers scan action output for known warning or error strings and report these inline.
##[add-matcher]/home/runner/work/_actions/actions/setup-node/v1/.github/eslint-stylish.json
##[debug]Added matchers: 'eslint-stylish'. Problem matchers scan action output for known warning or error strings and report these inline.
##[add-matcher]/home/runner/work/_actions/actions/setup-node/v1/.github/eslint-compact.json
##[debug]Added matchers: 'eslint-compact'. Problem matchers scan action output for known warning or error strings and report these inline.
##[debug]Node Action run completed with exit code 0
##[debug]Finished: run
##[debug]Evaluating: inputs.portal_id
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'portal_id'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: inputs.personal_access_key
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'personal_access_key'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating condition for step: 'run'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: run
##[debug]Loading inputs
##[debug]Evaluating: format('npx --yes --package=@hubspot/cli@latest --call=''hs upload {0} {1} --use-env''
##[debug]', inputs.src_dir, inputs.dest_dir)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'npx --yes --package=@hubspot/cli@latest --call=''hs upload {0} {1} --use-env''
##[debug]'
##[debug]..Evaluating Index:
##[debug]....Evaluating inputs:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'src_dir'
##[debug]..=> '.'
##[debug]..Evaluating Index:
##[debug]....Evaluating inputs:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'dest_dir'
##[debug]..=> 'dw-theme-v2'
##[debug]=> 'npx --yes --package=@hubspot/cli@latest --call=''hs upload . dw-theme-v2 --use-env''
##[debug]'
##[debug]Result: 'npx --yes --package=@hubspot/cli@latest --call=''hs upload . dw-theme-v2 --use-env''
##[debug]'
##[debug]Loading env
Run npx --yes --package=@hubspot/cli@latest --call='hs upload . dw-theme-v2 --use-env'
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/0a00461f-864[5](https://github.com/Digital-Woods/digital-woods-theme-v2/actions/runs/10448523239/job/28929438043#step:3:5)-47f0-b722-c90fbc93940f.sh
npm warn deprecated inflight@1.0.[6](https://github.com/Digital-Woods/digital-woods-theme-v2/actions/runs/10448523239/job/28929438043#step:3:6): This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@[7](https://github.com/Digital-Woods/digital-woods-theme-v2/actions/runs/10448523239/job/28929438043#step:3:7).2.3: Glob versions prior to v9 are no longer supported
/usr/bin/env: ‘node --no-deprecation’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
Error: Process completed with exit code [12](https://github.com/Digital-Woods/digital-woods-theme-v2/actions/runs/10448523239/job/28929438043#step:3:12)7.
##[debug]Finished: run
##[debug]Finishing: HubSpot Deploy Action

**Comment by OliverBojahrS24** [comment]
Same here ... please help

**Comment by MGFNolan-BJSS** [comment]
Also experiencing this issue.

**Comment by jsines** [comment]
Hello, looking into this issue, I've tried to reproduce on my end with a test theme and the deploy action appears to run fine. Can anyone confirm this is still a problem on their end? Since OP close the issue I assume it has resolved on its own for them.

**Comment by MGFNolan-BJSS** [comment]
> Hello, looking into this issue, I've tried to reproduce on my end with a test theme and the deploy action appears to run fine. Can anyone confirm this is still a problem on their end? Since OP close the issue I assume it has resolved on its own for them.

Hello! This issue stopped occurring as of today, not sure when. I tried a deployment around 8 hours ago which worked fine. More info on this community post:

https://community.hubspot.com/t5/CMS-Development/Github-deploy-action-failing-exit-127/td-p/1028749

**Comment by ajilityj** [comment]
@jsines i am still encountering the problem on my end. i had no issues up until last night and now i cannot deploy.

**Comment by OliverBojahrS24** [comment]
From my side I can also confirm it is fixed. Maybe it was a problem on Github side. Still worth looking into it I'd say.

**Comment by jsines** [comment]
@ajilityj Are your error longs the same as OPs? if you're able to reproduce the issue in a public repo, or have steps to reliably reproduce it, I'd be happy to take a look. But with everything working fine on my end I've got little to work off. If it's suddenly working for others again I'm inclined to believe this is a blip on GH's end. If the problem continues you may have better luck reverting to [uploading manually with the CLI in the meantime ](https://developers.hubspot.com/docs/cms/developer-reference/local-development-cli#upload-files) and checking back to see if the GH action is working again in a few days.

It looks like GH was doing some work on Actions that may have caused some instability last week that could be related: https://www.githubstatus.com/incidents/mrpx4trfk45z
